### ISSUE TITLE
show blank at main page

### ISSUE THREAD

**Issue by LJ8116** [duytq94/flutter-chat-demo#15] opened 2019-06-05 08:53 UTC
after sign in with my google account, there is nothing on main page, how to create one chat ?

**Comment by duytq94** [comment] 2019-06-05 10:23
You run your own project or run this demo, if you run your project, please use another account to sign in, so you can see the others and chat with them.

**Comment by duytq94** [comment] 2019-06-05 10:36
The example I just recheck, nothing wrong happen.
If you run your own project, please use another account to sign in, so you can see the others and chat with them.

**Comment by dasirahul7** [comment] 2019-06-12 12:14
I  think your firebase database don't have more than 1 user might be, add 2-3 users then it will show list of users at main page.

**Comment by duytq94** [comment] 2019-06-12 14:37
I'll close this issue since it's not a bug.
Anyway, feel free to keep discussing.

**Closed by duytq94** 2019-06-12 14:37 UTC
